/*
 * File: app/view/documental/Details.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ArqAdmin.view.documental.Details', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.documentaldetails',

    requires: [
        'ArqAdmin.view.documental.DetailsViewModel',
        'Ext.panel.Panel',
        'Ext.form.field.Display'
    ],

    viewModel: {
        type: 'documentaldetails'
    },
    reference: 'details',
    autoScroll: true,
    cls: 'display-panel',
    defaults: {
        bodyPadding: '6 0 0',
        margin: '4 0 0'
    },
    layout: 'anchor',
    bodyPadding: '4 8 0',

    items: [
        {
            xtype: 'panel',
            ui: 'light',
            defaults: {
                labelWidth: 150
            },
            collapsible: true,
            title: 'Dados de Cadastro',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'displayfield',
                    fieldLabel: 'Registro nº',
                    bind: {
                        value: '{record.id}'
                    }
                },
                {
                    xtype: 'displayfield',
                    fieldLabel: 'Espécie Documental',
                    bind: {
                        hidden: '{!record.especiedocumentalNome}',
                        value: '{record.especiedocumentalNome}'
                    }
                },
                {
                    xtype: 'displayfield',
                    fieldLabel: 'Notação Pré-existente',
                    bind: {
                        hidden: '{!record.notacaoPreexistente}',
                        value: '{record.notacaoPreexistente}'
                    }
                },
                {
                    xtype: 'displayfield',
                    fieldLabel: 'Notação AHSP',
                    bind: {
                        hidden: '{!record.notacao}',
                        value: '{record.notacao}'
                    }
                },
                {
                    xtype: 'displayfield',
                    fieldLabel: 'Ano',
                    bind: {
                        hidden: '{!record.ano}',
                        value: '{record.ano}'
                    }
                },
                {
                    xtype: 'displayfield',
                    fieldLabel: 'Data',
                    bind: {
                        hidden: '{!record.dataDoc}',
                        value: '{record.dataDoc}'
                    }
                },
                {
                    xtype: 'displayfield',
                    fieldLabel: 'Estado de Conservação',
                    bind: {
                        hidden: '{!record.conservacaoEstado}',
                        value: '{record.conservacaoEstado}'
                    }
                },
                {
                    xtype: 'displayfield',
                    fieldLabel: 'Processo nº',
                    bind: {
                        hidden: '{!record.processoNum}',
                        value: '{record.processoNum}'
                    }
                },
                {
                    xtype: 'displayfield',
                    fieldLabel: 'Qtde. de  Documentos',
                    bind: {
                        hidden: '{!record.quantidadeDoc}',
                        value: '{record.quantidadeDoc}'
                    }
                },
                {
                    xtype: 'displayfield',
                    fieldLabel: 'Interessado',
                    bind: {
                        hidden: '{!record.interessado}',
                        value: '{record.interessado}'
                    }
                },
                {
                    xtype: 'displayfield',
                    fieldLabel: 'Assunto',
                    bind: {
                        hidden: '{!record.assunto}',
                        value: '{record.assunto}'
                    }
                },
                {
                    xtype: 'displayfield',
                    fieldLabel: 'Uso',
                    bind: {
                        hidden: '{!record.dtUsoUso}',
                        value: '{record.dtUsoUso}'
                    }
                },
                {
                    xtype: 'displayfield',
                    fieldLabel: 'Notas',
                    bind: {
                        hidden: '{!record.notas}',
                        value: '{record.notas}'
                    }
                }
            ]
        },
        {
            xtype: 'panel',
            ui: 'light',
            defaults: {
                labelWidth: 150
            },
            collapsible: true,
            title: 'Dados de Endereço',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'displayfield',
                    fieldLabel: 'Endereço',
                    bind: {
                        hidden: '{!record.dtEndereco}',
                        value: '{record.dtEndereco}'
                    }
                },
                {
                    xtype: 'displayfield',
                    fieldLabel: 'Complemento',
                    bind: {
                        hidden: '{!record.dtEndComplemento}',
                        value: '{record.dtEndComplemento}'
                    }
                },
                {
                    xtype: 'displayfield',
                    fieldLabel: 'Endereço Atual',
                    bind: {
                        hidden: '{!record.dtEnderecoAtual}',
                        value: '{record.dtEnderecoAtual}'
                    }
                },
                {
                    xtype: 'displayfield',
                    fieldLabel: 'Complemento',
                    bind: {
                        hidden: '{!record.dtEndatualComplemento}',
                        value: '{record.dtEndatualComplemento}'
                    }
                }
            ]
        },
        {
            xtype: 'panel',
            ui: 'light',
            defaults: {
                labelWidth: 150
            },
            collapsible: true,
            title: 'Dados de Autoria',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'displayfield',
                    fieldLabel: 'Autor',
                    bind: {
                        hidden: '{!record.dtAutor}',
                        value: '{record.dtAutor}'
                    }
                },
                {
                    xtype: 'displayfield',
                    fieldLabel: 'Construtor',
                    bind: {
                        hidden: '{!record.dtConstrutor}',
                        value: '{record.dtConstrutor}'
                    }
                },
                {
                    xtype: 'displayfield',
                    fieldLabel: 'Proprietário',
                    bind: {
                        hidden: '{!record.dtProprietario}',
                        value: '{record.dtProprietario}'
                    }
                },
                {
                    xtype: 'displayfield',
                    fieldLabel: 'Notas',
                    bind: {
                        hidden: '{!record.dtNotas}',
                        value: '{record.dtNotas}'
                    }
                }
            ]
        },
        {
            xtype: 'panel',
            ui: 'light',
            defaults: {
                labelWidth: 150
            },
            collapsible: true,
            title: 'Localização Física',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'displayfield',
                    fieldLabel: 'Sala',
                    bind: {
                        hidden: '{!record.lcSalaSala}',
                        value: '{record.lcSalaSala}'
                    }
                },
                {
                    xtype: 'displayfield',
                    fieldLabel: 'Móvel',
                    bind: {
                        hidden: '{!record.lcMovelMovel}',
                        value: '{record.lcMovelMovel}'
                    }
                },
                {
                    xtype: 'displayfield',
                    fieldLabel: 'Movel nº',
                    bind: {
                        hidden: '{!record.lcMovelNum}',
                        value: '{record.lcMovelNum}'
                    }
                },
                {
                    xtype: 'displayfield',
                    fieldLabel: 'Compartimento',
                    bind: {
                        hidden: '{!record.lcCompartimentoCompartimento}',
                        value: '{record.lcCompartimentoCompartimento}'
                    }
                },
                {
                    xtype: 'displayfield',
                    fieldLabel: 'Compartimento nº',
                    bind: {
                        hidden: '{!record.lcCompartimentoNum}',
                        value: '{record.lcCompartimentoNum}'
                    }
                },
                {
                    xtype: 'displayfield',
                    fieldLabel: 'Acondicionamento',
                    bind: {
                        hidden: '{!record.lcAcondicionamentoAcondicionamento}',
                        value: '{record.lcAcondicionamentoAcondicionamento}'
                    }
                },
                {
                    xtype: 'displayfield',
                    fieldLabel: 'Acondicionamento nº',
                    bind: {
                        hidden: '{!record.lcAcondicionamentoNum}',
                        value: '{record.lcAcondicionamentoNum}'
                    }
                },
                {
                    xtype: 'displayfield',
                    fieldLabel: 'Página',
                    bind: {
                        hidden: '{!record.lcPagina}',
                        value: '{record.lcPagina}'
                    }
                }
            ]
        },
        {
            xtype: 'panel',
            ui: 'light',
            defaults: {
                labelWidth: 150
            },
            collapsible: true,
            title: 'Classificação',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'displayfield',
                    fieldLabel: 'Fundo',
                    bind: {
                        hidden: '{!record.fundoNome}',
                        value: '{record.fundoNome}'
                    }
                },
                {
                    xtype: 'displayfield',
                    fieldLabel: 'Subfundo',
                    bind: {
                        hidden: '{!record.subfundoNome}',
                        value: '{record.subfundoNome}'
                    }
                },
                {
                    xtype: 'displayfield',
                    fieldLabel: 'Grupo',
                    bind: {
                        hidden: '{!record.grupoNome}',
                        value: '{record.grupoNome}'
                    }
                },
                {
                    xtype: 'displayfield',
                    fieldLabel: 'Subgrupo',
                    bind: {
                        hidden: '{!record.subgrupoNome}',
                        value: '{record.subgrupoNome}'
                    }
                },
                {
                    xtype: 'displayfield',
                    fieldLabel: 'Série',
                    bind: {
                        hidden: '{!record.serieNome}',
                        value: '{record.serieNome}'
                    }
                },
                {
                    xtype: 'displayfield',
                    fieldLabel: 'Subsérie',
                    bind: {
                        hidden: '{!record.subserieNome}',
                        value: '{record.subserieNome}'
                    }
                },
                {
                    xtype: 'displayfield',
                    fieldLabel: 'Dossiê',
                    bind: {
                        hidden: '{!record.dossieNome}',
                        value: '{record.dossieNome}'
                    }
                }
            ]
        }
    ]

});