/*
 * File: app/view/documental/Form.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ArqAdmin.view.documental.Form', {
    extend: 'Ext.form.Panel',
    alias: 'widget.documentalform',

    requires: [
        'ArqAdmin.view.documental.FormViewModel',
        'ArqAdmin.view.documental.FormViewController',
        'Ext.form.FieldSet',
        'Ext.form.field.ComboBox',
        'Ext.toolbar.Spacer',
        'Ext.button.Button',
        'Ext.form.field.Display',
        'Ext.form.trigger.Trigger',
        'Ext.form.field.TextArea'
    ],

    controller: 'documentalform',
    viewModel: {
        type: 'documentalform'
    },
    reference: 'form',
    autoScroll: true,
    cls: 'custom-form-panel',
    defaults: {
        padding: '6 12 5',
        layout: {
            type: 'vbox',
            align: 'stretch'
        }
    },
    bodyPadding: 10,
    header: false,
    title: 'Editar Documento',
    fieldDefaults: {
        labelWidth: 150,
        queryMode: 'local',
        forceSelection: true,
        typeAhead: true
    },

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'fieldset',
            title: 'Classificação Documental',
            items: [
                {
                    xtype: 'container',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'combobox',
                            flex: 1,
                            reference: 'acervoCombo',
                            fieldLabel: 'Classificação (Atalho)',
                            name: 'acervoId',
                            emptyText: 'Selecione uma classificação...',
                            displayField: 'acervo_nome',
                            queryMode: 'local',
                            store: 'Acervos',
                            valueField: 'id',
                            listeners: {
                                select: 'onAcervoComboSelect'
                            }
                        },
                        {
                            xtype: 'tbspacer',
                            width: 3
                        },
                        {
                            xtype: 'button',
                            margin: '3 0',
                            ui: 'default-toolbar-small',
                            glyph: 58895,
                            tooltip: 'Editar classificação',
                            tooltipType: 'title'
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    reference: 'classificFieldset',
                    border: '1 0 0 0',
                    itemId: 'classificFieldset',
                    margin: '10 0 0 ',
                    padding: '10 0 0',
                    defaults: {
                        queryMode: 'local'
                    },
                    referenceHolder: true,
                    collapsible: true,
                    title: 'Classificação',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'combobox',
                            reference: 'fundoCombo',
                            fieldLabel: 'Fundo',
                            name: 'fundoId'
                        },
                        {
                            xtype: 'combobox',
                            reference: 'subfundoCombo',
                            disabled: true,
                            fieldLabel: 'Subfundo',
                            name: 'subfundoId',
                            displayField: 'subfundo_nome',
                            store: 'classificacao.Subfundos',
                            valueField: 'id'
                        },
                        {
                            xtype: 'combobox',
                            reference: 'grupoCombo',
                            disabled: true,
                            fieldLabel: 'Grupo',
                            name: 'grupoId',
                            displayField: 'grupo_nome',
                            store: 'classificacao.Grupos',
                            valueField: 'id'
                        },
                        {
                            xtype: 'combobox',
                            reference: 'subgrupoCombo',
                            disabled: true,
                            fieldLabel: 'Subgrupo',
                            name: 'subgrupoId',
                            displayField: 'subgrupo_nome',
                            store: 'classificacao.Subgrupos',
                            valueField: 'id'
                        },
                        {
                            xtype: 'combobox',
                            reference: 'serieCombo',
                            disabled: true,
                            fieldLabel: 'Série',
                            name: 'serieId',
                            displayField: 'serie_nome',
                            store: 'classificacao.Series',
                            valueField: 'id'
                        },
                        {
                            xtype: 'combobox',
                            reference: 'subserieCombo',
                            disabled: true,
                            fieldLabel: 'Subsérie',
                            name: 'subserieId',
                            displayField: 'subserie_nome',
                            store: 'classificacao.Subseries',
                            valueField: 'id'
                        },
                        {
                            xtype: 'combobox',
                            reference: 'dossieCombo',
                            disabled: true,
                            fieldLabel: 'Dossiê',
                            name: 'dossieId',
                            displayField: 'dossie_nome',
                            store: 'classificacao.Dossies',
                            valueField: 'id'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'fieldset',
            defaults: {
                queryMode: 'local'
            },
            title: 'Dados Gerais',
            items: [
                {
                    xtype: 'displayfield',
                    fieldLabel: 'Registro nº',
                    name: 'id'
                },
                {
                    xtype: 'combobox',
                    reference: 'especiedocumentalCombo',
                    fieldLabel: 'Espécie Documental',
                    name: 'especiedocumentalId',
                    allowBlank: false,
                    allowOnlyWhitespace: false,
                    displayField: 'especiedocumental_nome',
                    store: 'classificacao.Especiedocumentais',
                    typeAhead: true,
                    valueField: 'id'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Notação Pré-existente',
                    name: 'notacaoPreexistente'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Notação AHSP',
                    name: 'notacao'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Ano',
                    name: 'ano',
                    enforceMaxLength: true,
                    maxLength: 4,
                    regex: /^(18|19)\d{2}|(20)([0-2])\d$/,
                    regexText: 'O ano inserido não é válido'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Data',
                    name: 'dataDoc'
                },
                {
                    xtype: 'container',
                    margin: '0 0 5',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'combobox',
                            flex: 1,
                            fieldLabel: 'Estado de Conservação',
                            name: 'conservacaoId',
                            displayField: 'conservacao_estado',
                            store: 'documental.Conservacoes',
                            valueField: 'id',
                            triggers: {
                                clear: {
                                    handler: function(field, trigger, e) {
                                        field.clearValue();
                                    },
                                    cls: 'x-form-clear-trigger'
                                }
                            }
                        },
                        {
                            xtype: 'tbspacer',
                            width: 3
                        },
                        {
                            xtype: 'button',
                            margin: '3 0',
                            ui: 'default-toolbar-small',
                            glyph: 58895,
                            tooltip: 'Editar estados de conservação',
                            tooltipType: 'title'
                        }
                    ]
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Processo nº',
                    name: 'processoNum'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Qtde. de  Documentos',
                    name: 'quantidadeDoc'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Interessado',
                    name: 'interessado'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Assunto',
                    name: 'assunto',
                    allowBlank: false,
                    allowOnlyWhitespace: false,
                    minLength: 3
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Uso',
                    name: 'dtUsoId'
                },
                {
                    xtype: 'textareafield',
                    fieldLabel: 'Notas',
                    name: 'notas'
                }
            ]
        },
        {
            xtype: 'fieldset',
            title: 'Dados de Endereço',
            items: [
                {
                    xtype: 'textfield',
                    fieldLabel: 'Endereço',
                    name: 'dtEndereco'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Complemento',
                    name: 'dtEndComplemento'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Endereço Atual',
                    name: 'dtEnderecoAtual'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Complemento',
                    name: 'dtEndatualComplemento'
                }
            ]
        },
        {
            xtype: 'fieldset',
            title: 'Dados de Autoria',
            items: [
                {
                    xtype: 'textfield',
                    fieldLabel: 'Autor',
                    name: 'dtAutor'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Construtor',
                    name: 'dtConstrutor'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Proprietário',
                    name: 'dtProprietario'
                },
                {
                    xtype: 'textareafield',
                    fieldLabel: 'Notas',
                    name: 'dtNotas'
                }
            ]
        },
        {
            xtype: 'fieldset',
            defaults: {
                queryMode: 'local'
            },
            title: 'Localização Física',
            items: [
                {
                    xtype: 'container',
                    margin: '0 0 5',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'combobox',
                            flex: 1,
                            fieldLabel: 'Sala',
                            name: 'lcSalaId',
                            displayField: 'sala',
                            store: 'localizacao.LcSalas',
                            valueField: 'id',
                            triggers: {
                                clear: {
                                    handler: function(field, trigger, e) {
                                        field.clearValue();
                                    },
                                    cls: 'x-form-clear-trigger'
                                }
                            }
                        },
                        {
                            xtype: 'tbspacer',
                            width: 3
                        },
                        {
                            xtype: 'button',
                            margin: '3 0',
                            ui: 'default-toolbar-small',
                            glyph: 58895,
                            tooltip: 'Editar salas',
                            tooltipType: 'title'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    margin: '0 0 5',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'combobox',
                            flex: 1,
                            fieldLabel: 'Móvel',
                            name: 'lcMovelId',
                            displayField: 'movel',
                            store: 'localizacao.LcMoveis',
                            valueField: 'id',
                            triggers: {
                                clear: {
                                    handler: function(field, trigger, e) {
                                        field.clearValue();
                                    },
                                    cls: 'x-form-clear-trigger'
                                }
                            }
                        },
                        {
                            xtype: 'tbspacer',
                            width: 3
                        },
                        {
                            xtype: 'button',
                            margin: '3 0',
                            ui: 'default-toolbar-small',
                            glyph: 58895,
                            tooltip: 'Editar móveis',
                            tooltipType: 'title'
                        }
                    ]
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Movel nº',
                    name: 'lcMovelNum'
                },
                {
                    xtype: 'container',
                    margin: '0 0 5',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'combobox',
                            flex: 1,
                            fieldLabel: 'Compartimento',
                            name: 'lcCompartimentoId',
                            displayField: 'compartimento',
                            store: 'localizacao.LcCompartimentos',
                            valueField: 'id',
                            triggers: {
                                clear: {
                                    handler: function(field, trigger, e) {
                                        field.clearValue();
                                    },
                                    cls: 'x-form-clear-trigger'
                                }
                            }
                        },
                        {
                            xtype: 'tbspacer',
                            width: 3
                        },
                        {
                            xtype: 'button',
                            margin: '3 0',
                            ui: 'default-toolbar-small',
                            glyph: 58895,
                            tooltip: 'Editar compartimentos',
                            tooltipType: 'title'
                        }
                    ]
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Compartimento nº',
                    name: 'lcCompartimentoNum'
                },
                {
                    xtype: 'container',
                    margin: '0 0 5',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'combobox',
                            flex: 1,
                            fieldLabel: 'Acondicionamento',
                            name: 'lcAcondicionamentoId',
                            displayField: 'acondicionamento',
                            store: 'localizacao.LcAcondicionamentos',
                            valueField: 'id',
                            triggers: {
                                clear: {
                                    handler: function(field, trigger, e) {
                                        field.clearValue();
                                    },
                                    cls: 'x-form-clear-trigger'
                                }
                            }
                        },
                        {
                            xtype: 'tbspacer',
                            width: 3
                        },
                        {
                            xtype: 'button',
                            margin: '3 0',
                            ui: 'default-toolbar-small',
                            glyph: 58895,
                            tooltip: 'Editar acondicionamentos',
                            tooltipType: 'title'
                        }
                    ]
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Acondicionamento nº',
                    name: 'lcAcondicionamentoNum'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Página',
                    name: 'lcPagina'
                }
            ]
        }
    ]

});