/*
 * File: app/view/documental/FormViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ArqAdmin.view.documental.FormViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.documentalform',

    onAcervoComboSelect: function(combo, records, eOpts) {
        var me = this,
            formPanel = me.getReferences().documentalForm,
            form = formPanel.getForm(),
            combosRefs = this.lookupReference('classificFieldset').getReferences(),
            values = records[0].getData();

        delete values.id;

        me.clearFilterCascadingCombos();
        form.setValues(values);
        me.changeDisableCascadingCombos();

        me.lookupReference('especiedocumentalCombo').focus(true, 180);
    }

});
