/*
 * File: app/view/dashboard/Container.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ArqAdmin.view.dashboard.Container', {
    extend: 'Ext.container.Container',
    alias: 'widget.dashboardcontainer',

    requires: [
        'ArqAdmin.view.dashboard.ContainerViewModel',
        'Ext.panel.Panel'
    ],

    viewModel: {
        type: 'dashboardcontainer'
    },
    reference: 'dashboardContainer',
    layout: 'border',

    items: [
        {
            xtype: 'panel',
            region: 'center',
            header: false,
            title: 'My Panel'
        }
    ]

});