/*
 * File: app/view/footer/Panel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ArqAdmin.view.footer.Panel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.footerpanel',

    requires: [
        'ArqAdmin.view.footer.PanelViewModel'
    ],

    viewModel: {
        type: 'footerpanel'
    },
    reference: 'footer',
    height: 250,
    width: 400,
    glyph: 61457,
    title: 'Histórico de iteração'

});